### ISSUE TITLE
Can I use it with "Sublime SFTP"?

### ISSUE THREAD

**Issue by marcus-at-localhorst** [DougTy/sublime-compare-side-by-side#1]
Sublime SFTP has a setting [diff_command](http://wbond.net/sublime_packages/sftp/settings#setting-diff_command) to call an external program like Winmerge. By default it uses the ST standard diff view.

Would it be possible to use **sublime-compare-side-by-side**?

**Comment by DougTy** [comment]
Been looking into it the past couple days, I think there's a way but it'll require a bit of patching.
Will let you know if it ends up working.

**Comment by DougTy** [comment]
Just uploaded a patch, should auto update from package control. I haven't tested it with the Sublime SFTP plugin specifically, but running the following from command line works in Windows:

```subl --command "sbs_compare_files {\"A\":\"file1.txt\", \"B\":\"file2.txt\"}"```

If you're on OSX or Linux you should be able to use single quotes around the command and avoid having to escape the argument quotes:

```subl --command 'sbs_compare_files {"A":"file1.txt", "B":"file2.txt"}'```

Sticking this in a JSON string for SFTP's ```diff_command``` setting will likely require additional escaping.
Also seems to work with ```sublime_text``` if you can't use ```subl``` for whatever reason.

The one caveat: Sublime must be open before running the command. If it's closed, it just seems to launch whilst completely ignoring the compare command. No idea why this happens or how to fix it, but I figure this shouldn't be much of an issue since you'll already have Sublime open anyway with the SFTP plugin.

Let me know how this works for you.

**Comment by marcus-at-localhorst** [comment]
Thanks for this patch I tried it, but couldn't get it work.
Here is what I found out:

SFTP's `"diff_command": ["subl", "%1$s","%2$s"],` expects 3 parameters - program, file A, file B.
It's not possible to write anything else as parameters than the program to execute and the two files.

```
// error with sftp
"diff_command": ["subl --command", "%1$s","%2$s"],
// same error
"diff_command": ["subl", "--command \"sbs_compare_files {\\\"A\\\":\\\"%1$s\\\",\\\"B\\\":\\\"%2$s\\\"}\""],
// doesn't render %2$s anymore
"diff_command": ["subl", "%1$s","some param %2$s"],
```
I tried different versions, with crazy param masking but narrowed it down to the conclusion that only those plain parameters will work. No extra strings in there.

Since you have to call `subl -- command ...` it seems not possible to call the compare command from Sublime SFTP's side.
Although Sublime SFTP uses the Sublime Text internal diff if `diff_command` is not set.

Your patch is working fine from command line though!

Thanks for your effort!

**Comment by DougTy** [comment]
Huh, that's a rather funky way of doing things. I'm sure they had a good reason, though.

Unfortunately, ```subl -- command ...``` is the only interface Sublime gives us to run plugin commands externally (as far as I know). However, you should be able to get around this using a shell script.

Windows (.bat): ```subl --command "sbs_compare_files {\"A\":\"%1\", \"B\":\"%2\"}"```
Linux (.sh): ```subl --command 'sbs_compare_files {"A":"$1", "B":"$2"}'```
[unsure about OSX, probably the same as Linux]

This'll allow you to launch the comparison as simply ```script file1 file2``` without the argument mess.

You can then use this script (whatever.bat or whatever.sh) as the first parameter of ```diff_command```, and pass the two files to compare as parameters 2 and 3 normally (however the plugin wants it).

Hopefully this should work.

**Comment by marcus-at-localhorst** [comment]
Unfortunately I had no luck. I tried to escape the json params with `"""A""":` and combinations of backslashes etc. nothing. 
It even looks like the first sftp param only accepts an executable and no script. Because I am not able to run a simple *.cmd with `echo x >file.txt` as content (from that sftp setting)

This: `"diff_command": ["subl", "%1$s","%2$s"]` in the sftp settings works as expected.
I could now manually start the compare command after the remote file got opened in ST.

**Comment by DougTy** [comment]
I gave SFTP a try, and with a little wrestling, got it to work. Seemingly Windows requires a little extra effort to get the paths escaping properly and playing nicely with our command's arguments. 

Here's my batch file:
```
set file1=%~1
set file1=%file1:\=\\%
set file2=%~2
set file2=%file2:\=\\%
subl --command "sbs_compare_files {\"A\":\"%file1%\", \"B\":\"%file2%\"}"
``` 
I saved this in ```C:\Program Files\Sublime Text 3``` as ```compare.bat```

My SFTP user settings:
```"diff_command": ["C:\\Program Files\\Sublime Text 3\\compare.bat", "%1$s", "%2$s"]```

Right clicking a file and using SFTP's diff then correctly launches a side by side comparison for me.

Hopefully this works for you too, otherwise I'm really not sure if there are any other workarounds.
If it does, I'll look into including these scripts with the plugin.

**Comment by marcus-at-localhorst** [comment]
It's working! I would have never gotten so far. So you had to escape the backslashes of the two files, right? Windows batch file syntax is a mystery to me :)

I, just had to add the full path to `subl.exe` in the .bat (Portable Install/not added to PATH) and then it was opening the compare view as expected! Awesome!

Thank you so much for your work and for solving this!

**Comment by DougTy** [comment]
Awesome! Glad it works.

Came down to two things: escaping backslashes (second line replaces ```\``` with ```\\```), and removing extra quotes around the input that are added when the path has a space in it (squiggly in the first line).

I'll go ahead and close the issue now. Happy to help!
