### ISSUE TITLE
[ENHANCEMENT] Two colours for intraline diffs

### ISSUE THREAD

**Issue by aaaxx** [DougTy/sublime-compare-side-by-side#10]
Could you add a column-A/B setting for intraline diff colour like there is for full lines, so it looks like diffs on GitHub?

**Comment by DougTy** [comment]
Sorry for the late response. Haven't much time to work on this lately.
Good idea, though. I've released an update that contains that functionality.

Because it can be difficult to find colours that work with a wide variety of different colour schemes & themes, I've left the default values to the same blue colour. This can be changed by adding `modified_colour_deletion` and `modified_colour_addition` to your user settings for the plugin.

Thanks!

**Comment by aaaxx** [comment]
Wow, thanks so much.

How exactly do I update it? Package Control says there are no packages ready to upgrade.

**Comment by DougTy** [comment]
It should update automatically. You may also need to restart Sublime. The
updated version is 1.12.0 to be sure.
