### ISSUE TITLE
Display file location in compare view

### ISSUE THREAD

**Issue by sdruskat** [DougTy/sublime-compare-side-by-side#33]
When comparing files of the same name, it might be helpful to show the file location - e.g., the folder name containing the file - somewhere.

Sublimerge's "Compare with ..." does this in the tab, e.g., `file.txt - my-folder`.

I think putting this info in the tab is great, and alternatively or additionally putting it in the "Groups" side bar would work nicely as well.

**Comment by sdruskat** [comment]
Ah, just found this in the settings:

````
// should filenames show full paths underneath them?
"expanded_filenames": true,
````

Sorry to report that it doesn't work, i.e., paths aren't shown.

**Comment by DougTy** [comment]
My apologies, `expanded_filenames` was a bit of a misnomer--what this was referring to is the filenames in the dropdown when you right-click a tab and choose "Compare with...". It was left as an option because takes up a bit more space to display the files' directories, but I think that should always be displayed anyways, so I've removed this setting to avoid confusion.

I've released an update to show directory names if the files being compared have the same name, similar to how Sublime displays it in tabs normally.

Thanks!
