### ISSUE TITLE
XML colour definitions are appended to a JSON colour scheme file

### ISSUE THREAD

**Issue by Devenec** [DougTy/sublime-compare-side-by-side#36]
My active colour scheme is in JSON format (.sublime-color-scheme). An error is displayed when compare is performed, due to Compare Side-By-Side appending XML colour definitions to the JSON color scheme.

To reproduce: Set the active colour scheme to Monokai and perform compare.

**Comment by DougTy** [comment]
Had no idea there was a new JSON format! Thanks for letting me know, fixed.

**Comment by step-** [comment]
Just noting that [line 169](https://github.com/DougTy/sublime-compare-side-by-side/blob/89e8329703d7045f34e02ae719047a852aaf993a/sbs_compare.py) and [line 174](https://github.com/DougTy/sublime-compare-side-by-side/blob/89e8329703d7045f34e02ae719047a852aaf993a/sbs_compare.py) will always lead to `scheme_json = False` even when the json scheme is in use. While it can be a problem with this fix, I don't think it drives the behavior I'm seeing in #42 because there I don't see the message dialog from [line 168](https://github.com/DougTy/sublime-compare-side-by-side/blob/89e8329703d7045f34e02ae719047a852aaf993a/sbs_compare.py), so line 169 isn't hit in that case.

**Comment by DougTy** [comment]
The try/except starting on line 163 was to solve #31 where `sublime.load_resource` would produce an error after upgrading from ST2 to ST3, so a default XML scheme is created so that the diff still has some colour (albeit not the user's chosen colour scheme). Outside of that one edge case, `sublime.load_resource` should work for both JSON and XML schemes and not hit the except block.

The fix for this issue was in 1d1a28c, which added the try/except on 173 (which, as you've discovered in #42, appears to not work with certain colour schemes). This fix works, just only for valid JSON.

**Comment by DougTy** [comment]
Properly fixed now in e6efcf7, thanks for the help @step-!
