### ISSUE TITLE
Possible OSX incompatibility

### ISSUE THREAD

**Issue by mastef** [DougTy/sublime-compare-side-by-side#41]
When I compare 2 files, since recently the comparison windows are both empty.

After opening the console, there's the error : `AttributeError: 'Window' object has no attribute 'set_menu_visible'`

This only happened recently, and I suppose is related to #26

**Comment by DougTy** [comment]
Thanks for making a separate issue.

Can you check what build/version of Sublime you're running?

**Comment by DougTy** [comment]
@mastef If you could please check your Sublime build number, I'd like to verify if this is just simply an issue of an outdated ST3 install or an actual API compatibility or not, before I make any changes. Thanks.

**Comment by mastef** [comment]
I don't have the latest version, but from the linked ticket it looks like
this is an OSX incompability. Managed to get the plug in running by setting
`hide_menu: false` ( or `true`, can't recall ) in the settings.

Nevertheless it is good practice to check if a property exists if it hasn't
been in the API from the start, right.

The same way as I have to support Chrome extensions for people who didn't
auto update.

( Although I understand the difficulty with Sublime as the API docs don't
seem to be versioned. )

**Comment by mastef** [comment]
aziz/DistractionFreeWindow#19 mentioned OSX on 3114

**Comment by DougTy** [comment]
@mastef As I have no way of testing whether this is an OSX issue myself or just due to running an outdated version of Sublime, I would very much appreciate it if you could check your build number so we know if you're running a build prior to when these API functions were added or not.

I highly doubt this is OSX incompatibility, as a great deal of the plugin's users are on OSX and I haven't received any bug reports on this before, however until we can check out that version number I'd rather not jump to any conclusions.

The [release notes](https://www.sublimetext.com/updates/3/dev/release_notes.html) say that those functions were added in build 3116, so if the guy in the ticket you've linked was using 3114, I'm afraid they came to the wrong conclusion that it was an OSX incompatibility issue. I'd just like to make sure that this is the case with you as well before proceeding with anything, as it would be unwise to write any code before fully diagnosing the problem.

**Comment by mastef** [comment]
OK - I'll check it later today when I'm back on that machine. But no matter if it's version related or OSX related, isn't it just adding `if hasattr(new_window, 'set_menu_visible'):` or 
```python
try:
    new_window.set_menu_visible()
except AttributeError:
    print("set menu visible not available")
```
? Or are you looking into adding `<3116` version checks?

**Comment by DougTy** [comment]
@mastef The build without these API functions is over 2 years old now, and was a pre-release, development, beta version. I don't really think that warrants long term support. I would like to avoid adding unnecessary version checks & creating fallbacks for pre-release versions (as opposed to outright removing features) for the sake of clarity and cleanliness.

If it's an issue with OSX I can look at changing the defaults for OSX, otherwise my recommendation would be to simply update your ST3. I don't believe there are any breaking changes at all that would cause incompatibility with plugins or anything, so there should be no reason not to update.

Can reopen if it is an OSX problem, but my bet is on it just being an old version. If updating is not possible for some reason, `hide_menu: false` should be a valid workaround, however I will not be supporting old pre-release versions of ST3. Sorry.

**Comment by mastef** [comment]
@DougTy Unfortunately not everybody can keep their versions updated due to certain customisations. ST has been basically in "beta" since 2013 until less than a year ago. Your plugin was working fine until that recent patch. But if adding a simple condition is so hard, and warrants this much discussion - that's up to you. Then this ticket will be here to help others who might've run into the same issue...
