### ISSUE TITLE
Error when using Celeste color scheme

### ISSUE THREAD

**Issue by agj** [DougTy/sublime-compare-side-by-side#42]
I get the following error if I have the Celeste color scheme active, and it goes away if I have choose Monokai.

_Error loading colour scheme Packages/User/SBSCompareTheme.tmTheme: Error parsing plist xml: expected < in file Packages/User/SBSCompareTheme.tmTheme on line: 1_

Thanks lots for this package that I use very often. :)

**Comment by DougTy** [comment]
@agj 

Thanks for reporting, I'll take a closer look at this once I have a bit more free time.

In the mean time, can you take a look at what build of Sublime you're using?
Also, are you on OSX by any chance?
Thanks.

**Comment by agj** [comment]
Right! I'm sorry for not providing any useful information, that was thoughtless of me. Yes, I'm on macOS High Sierra (10.13.5), and my version of Sublime is 3.1.1 build 3176.

**Comment by agj** [comment]
Let me know if there's anything I can do to help. I have only limited Python abilities though, and I'm not familiar with how packages are written for Sublime, or its internals, but if you want me to test some code or attempt some specific tests, hit me.

**Comment by step-** [comment]
Same error message here. I'm on Linux. I took a look at the package directory. The generated color scheme is a mix of json and xml. I think the python script wrongly determines that the legacy colorscheme file format is in use, while it isn't. I'm trying to work around this issue by adding `scheme_json = True` after line 177, the `try`-`except` block. But I don't know what steps to take to make my change "take" in the Package folder structure. That's because I installed this plugin with Package Control, which hides away the github package structure (I'm a new ST3 user).

**Comment by step-** [comment]
I made some progress. This is what really happens when `scheme = json.loads( scheme )` is executed under `try` (now commented out):
```
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 367, in raw_decode
ValueError: Expecting property name enclosed in double quotes: line 6 column 9 (char 92)
```
I imagine it means that the Celeste color scheme file itself has some syntax issues. I'll go check. Meanwhile, my take away is that `try: json.load()` isn't solid enough to test whether the json color scheme format is in use.

**Comment by step-** [comment]
Ok, work-around attached. It's a patched Celeste color scheme json file. Exit ST completely, then copy the attached file to a folder under `Packages/Users`. Mine is in  `Packages/User/Color Scheme - Default.extracted/Celeste.sublime-color-scheme`. Then delete files `Packages/User/SBSCompareScheme.sublime-color-scheme` and  `Packages/User/SBSCompareTheme.tmTheme` and start ST. Now try to compare something, i.e., select a word and right-click to mark the selection for comparison. Do the same for another selection. Finally right-click and choose _Compare Selections_. It works for me.

[Celeste.sublime-color-scheme.zip](https://github.com/DougTy/sublime-compare-side-by-side/files/2171992/Celeste.sublime-color-scheme.zip)

The attached file is a valid json file derived from the original one that is distributed with ST3. The original file includes invalid comments `//` and invalid commas after the last element of severl json arrays. However, since it works for Sublime HQ Pty Ltd, I guess they must have written their own little json pre-processor before they pass valid json to `json.loads()`.

@DougTy, I gave up looking for a patch after I realized that the Celeste scheme json syntax is augmented by design. You should consider sanitizing the json data before it goes through `json.load()` otherwise the plugin could fail with other color scheme files that use the same augmented syntax.

One last issue. With the patched color scheme loaded, if I select _Preferences... > Color Scheme..._ in the ST menu, this error message shows up:
  * Error loading colour scheme Packages/User/SBSCompareTheme.tmTheme: Bad XML.

Regardless, now the plugin works for me (limited testing). Thank you very much for this plugin!

**Comment by DougTy** [comment]
@step- Thanks for debugging!
You were right on the money, the issue definitely seems to have been invalid JSON in Celeste.

Luckily, Sublime's API apparently has its own function for reading JSON now which can handle comments & other invalidness, so I've updated the plugin to use that instead of the standard `json.loads`

The fix should be on package control within about an hour. 
It works for me on Linux, @agj can you confirm if this fix works for you on OSX?

Cheers.

**Comment by agj** [comment]
Amazing detective work, @step-! It's working for me now with the patched color scheme, so I expect the new version to work. Thank you, @DougTy for providing it, and I'll let you know how it goes when it shows up in Package Control. :)

Sublime Text is probably using [JSON5](https://json5.org/) or a similar enhanced version of JSON...

**Comment by step-** [comment]
@DougTy and @agj, glad I could help! I learned a few things from debugging this issue.
> Sublime Text is probably using JSON5 or a similar enhanced version of JSON...

Maybe it's time for me to update [JSON.sh](https://github.com/step-/JSON.sh) :)

**Comment by agj** [comment]
Woops, looks like it updated itself with no warning, and I was left waiting. Anyway, I can confirm that after the fix it's working, as expected. Woo!

**Comment by gitressa** [comment]
I was getting a similar error, with any color profile. I had a look in my folders, and I think I might have manually unpacked the SBS plugin when I first installed it. Removing SBS-related files in these three places:
- One file in /Cache/User (called something like Compare Side-By-Side?)
- The folder /Packages/Compare Side-By-Side
- Three files in /Packages/User/

... and reinstalling Compare Side-By-Side via the package management system at **Preferences > Package Control > Install Package** fixed the problem.

Thanks for a great tool!
