### ISSUE TITLE
Conflicting keybindings

### ISSUE THREAD

**Issue by nikhilhassija** [DougTy/sublime-compare-side-by-side#47]
**Problem**
Current default keybindings for the package, `alt+shift+up` and `alt+shift+down`, conflict with keybinding for ST3 built-in command `select_lines`. This leads to over-riding the latter's keybinding, and thus making that command inaccessible. 

**Proposed Solution**
Change keybindings to something that doesn't conflict. Suggestions for `sbs_next_diff` and `sbs_prev_diff` pairs
 - `alt+n` and `alt+p`
 - `alt+n` and `alt+shift+n`
 - [`alt+d`, `up`] and [`alt+d`, `down`]

**Comment by DougTy** [comment]
Hey thanks for reporting this, these must be newer default keybinds as they were definitely not in use when I first implemented this feature. Is Ctrl+Shift+Up/Down okay? I don't believe these are in use by ST3 for anything currently.

**Comment by nikhilhassija** [comment]
Hey, `Ctrl+Shift+Up/Down` is also part ST3's built-in shortcuts, these are used for moving lines up and down. How about `alt+n/p` for next and prev diffs? I checked, these are combinations are unused, so they won't conflict with any of the default keybindings.

**Comment by DougTy** [comment]
Sorry I haven't been able to get to this. Thanks for taking it up, I appreciate it.
I'll accept #48 as those are the simplest bindings & are common convention in other programs too.
Cheers!

**Comment by utluiz** [comment]
FYI `alt+n`, which translates to `option+n` in MacOS, conflicts with the default system shortcut for   inserting a tilde (`˜`), which can be used by itself or with latin characters such as `ã`, `õ`, `ñ`. I have to disable this plugin while writing in Portuguese.

**Comment by DougTy** [comment]
Good to know, thanks for bringing this to light. Unfortunately we will always find some conflicts with whatever defaults we set, however as an alternative to disabling the plugin when not in use, you can change your key bindings for the plugin to something that doesn't conflict for you.

In `Preferences > Key Bindings`:

1. Blank out & disable the plugin's defaults
```
	{ "keys": ["alt+n"], "command": "" },
	{ "keys": ["alt+p"], "command": "" },
```

2. Set your new key bindings
```
	{ "keys": ["alt+shift+n"], "command": "sbs_next_diff" },
	{ "keys": ["alt+shift+p"], "command": "sbs_prev_diff" }
```

Hopefully this helps. I can definitely see that being an annoying problem to deal with.

**Comment by atempel** [comment]
I had the same problem with "Alt+n", but shouldn't it be solved on the **default settings**?

I had to find these two commands you can put on Sublime's console to debug inputs and commands:
`sublime.log_commands(True)` and `sublime.log_input(True)`

So when pressing "Alt+n" it printed this:
```
key evt: alt+n
command: sbs_next_diff
key evt: alt+n
command: sbs_next_diff
```
Even if you can change that on the user-preferences the package should not change or override operational system shortcuts or configurations without being open about it.
My recommendation is to change this default shortcut on the package, maybe for something like `super+alt+>` along with `super+alt+<` for previous diff for example.

Had to uninstall the package so I could use the tilde again on the app. Surely english speaking countries don't have this problem since there's no accents at all, but I had to go after all that trouble to find the solution, since this issue is closed, the access to it from googling or anything else is pretty hard.
