### ISSUE TITLE
Issues with word wrap

### ISSUE THREAD

**Issue by schwarze** [DougTy/sublime-compare-side-by-side#5]
Hi,
it seems that the synchronized scrolling is off by a few lines if word wrapping is enabled.
At least it can be fixed by turning word wrap off for both sides.
Maybe this could / should be done automatically when the plugin has started!?

Thanks, Matthias

**Comment by DougTy** [comment]
Hi Matthias,
I'm looking into it.

Unfortunately I'm not sure if word wrap can be properly fixed or not. The only solution I can think of is to pad the opposite view with empty lines to make up for the offset, but Sublime's plugin API doesn't seem to give me access to any information regarding wrapping (not to mention that the line difference would change any time the window is resized anyway). I'll keep searching and experimenting.

Otherwise, I can automatically disable word wrap when the comparison output views open. This won't fix word wrap, but it'll ensure that it's forced off in case the user's `word_wrap` setting is set to true. Is this the case for you? My comparison windows default to having word wrap disabled, so this is all that I can think of that would be causing it to turn on like that.

**Comment by schwarze** [comment]
Hi Doug,

force-disabling word wrap _(yes, it's always on for me)_ for the comparison views would be perfectly fine!
Is it possible to turn off word wrapping for just these views, or is it a global setting in sublime?

Thanks again,
Matthias

**Comment by DougTy** [comment]
Alright, I've pushed the patch. Should update in Package Control within about an hour.
Please let me know if this did not resolve the issue for you.

Doug

**Comment by schwarze** [comment]
Perfect, works like a charm!
Thanks for the fast patch!!

**Comment by DougTy** [comment]
Awesome, happy to help!
